In [1]:
import sqlite3
import pandas as pd

df = pd.read_csv('../processed/customer_features.csv')

conn = sqlite3.connect('../sql/customer_retention.db')

df.to_sql(
    'customer_features',
    conn,
    if_exists='replace',
    index=False
)

print("Database Created Successfully")

Database Created Successfully

In [4]:
query = """
PRAGMA table_info(customer_features);
"""

pd.read_sql_query(query, conn)

    cid                    name     type  notnull dflt_value  pk
0     0             Customer ID  INTEGER        0       None   0
1     1                     Age  INTEGER        0       None   0
2     2                  Gender     TEXT        0       None   0
3     3          Item Purchased     TEXT        0       None   0
4     4                Category     TEXT        0       None   0
5     5   Purchase Amount (USD)  INTEGER        0       None   0
6     6                Location     TEXT        0       None   0
7     7                    Size     TEXT        0       None   0
8     8                   Color     TEXT        0       None   0
9     9                  Season     TEXT        0       None   0
10   10           Review Rating     REAL        0       None   0
11   11     Subscription Status     TEXT        0       None   0
12   12           Shipping Type     TEXT        0       None   0
13   13        Discount Applied     TEXT        0       None   0
14   14         Promo Code Used     TEXT        0       None   0
15   15      Previous Purchases  INTEGER        0       None   0
16   16          Payment Method     TEXT        0       None   0
17   17  Frequency of Purchases     TEXT        0       None   0
18   18         Frequency Score     REAL        0       None   0
19   19      Subscription Score  INTEGER        0       None   0
20   20    Previous Purchases_N     REAL        0       None   0
21   21       Frequency Score_N     REAL        0       None   0
22   22         Review Rating_N     REAL        0       None   0
23   23        Loyalty Score V1     REAL        0       None   0
24   24            Loyalty Band     TEXT        0       None   0
25   25  Promo Dependency Score  INTEGER        0       None   0
26   26  Promo Dependency Level     TEXT        0       None   0
27   27    Customer Value Score  INTEGER        0       None   0
28   28              Value Tier     TEXT        0       None   0
29   29        Customer Segment     TEXT        0       None   0

In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('../sql/customer_retention.db')

query = """
SELECT "Customer Segment",
       COUNT(*) AS Customer_Count
FROM customer_features
GROUP BY "Customer Segment"
"""

result = pd.read_sql_query(query, conn)

result

  Customer Segment  Customer_Count
0   Bargain Hunter            1268
1  Growth Customer            1073
2   Low Engagement             584
3     VIP Loyalist             975

In [7]:
query = """
SELECT "Value Tier",
       COUNT(*) AS Customer_Count
FROM customer_features
GROUP BY "Value Tier"
"""

pd.read_sql_query(query, conn)

  Value Tier  Customer_Count
0     Bronze             975
1       Gold             973
2   Platinum             975
3     Silver             977

In [8]:
query = """
SELECT "Promo Dependency Level",
       COUNT(*) AS Customer_Count
FROM customer_features
GROUP BY "Promo Dependency Level"
"""

pd.read_sql_query(query, conn)

  Promo Dependency Level  Customer_Count
0                   High            1677
1                    Low            2223

In [9]:
query = """
SELECT Category,
       SUM("Purchase Amount (USD)") AS Revenue
FROM customer_features
GROUP BY Category
ORDER BY Revenue DESC
"""

pd.read_sql_query(query, conn)

      Category  Revenue
0     Clothing   104264
1  Accessories    74200
2     Footwear    36093
3    Outerwear    18524

In [10]:
query = """
SELECT "Customer Segment",
       ROUND(AVG("Purchase Amount (USD)"),2) AS Avg_Spend
FROM customer_features
GROUP BY "Customer Segment"
ORDER BY Avg_Spend DESC
"""

pd.read_sql_query(query, conn)

  Customer Segment  Avg_Spend
0     VIP Loyalist      79.66
1  Growth Customer      55.80
2   Bargain Hunter      52.76
3   Low Engagement      49.05

In [11]:
query = """
SELECT "Loyalty Band",
       COUNT(*) AS Customer_Count
FROM customer_features
GROUP BY "Loyalty Band"
"""

pd.read_sql_query(query, conn)

  Loyalty Band  Customer_Count
0          NaN            1131
1         High             692
2          Low             693
3       Medium             692
4    Very High             692

In [13]:
query = """
SELECT Category
FROM customer_features
"""

pd.read_sql_query(query, conn)

         Category
0        Clothing
1        Clothing
2        Clothing
3        Footwear
4        Clothing
...           ...
3895     Clothing
3896  Accessories
3897  Accessories
3898     Footwear
3899  Accessories

[3900 rows x 1 columns]

In [15]:
query = """
SELECT COUNT(*) AS total_customers
FROM customer_features
"""

pd.read_sql_query(query, conn)

   total_customers
0             3900

In [17]:
query = """
SELECT SUM("Purchase Amount (USD)") AS Total_Revenue
FROM customer_features
"""

pd.read_sql_query(query, conn)

   Total_Revenue
0         233081

In [19]:
query = """
SELECT ROUND(AVG("Purchase Amount (USD)"), 2) AS Avg_Purchase
FROM customer_features
"""
pd.read_sql_query(query, conn)

   Avg_Purchase
0         59.76

In [21]:
query = """
SELECT Category,
    SUM("Purchase Amount (USD)") AS Revenue
FROM customer_features
GROUP BY Category
ORDER BY Revenue DESC
"""

pd.read_sql_query(query, conn)

      Category  Revenue
0     Clothing   104264
1  Accessories    74200
2     Footwear    36093
3    Outerwear    18524